//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod wx_accounts;
pub mod wx_auto_replies;
pub mod wx_materials;
pub mod wx_menus;
pub mod wx_messages;
pub mod wx_pay_orders;
pub mod wx_pay_refunds;
pub mod wx_template_logs;
pub mod wx_templates;
pub mod wx_users;
