//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::wx_accounts::Entity as WxAccounts;
pub use super::wx_auto_replies::Entity as WxAutoReplies;
pub use super::wx_materials::Entity as WxMaterials;
pub use super::wx_menus::Entity as WxMenus;
pub use super::wx_messages::Entity as WxMessages;
pub use super::wx_pay_orders::Entity as WxPayOrders;
pub use super::wx_pay_refunds::Entity as WxPayRefunds;
pub use super::wx_template_logs::Entity as WxTemplateLogs;
pub use super::wx_templates::Entity as WxTemplates;
pub use super::wx_users::Entity as WxUsers;
