//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_accounts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub app_id: String,
    pub app_secret: String,
    pub account_name: String,
    pub account_type: i8,
    pub original_id: Option<String>,
    pub wechat_id: Option<String>,
    pub status: Option<i8>,
    pub message_mode: i8,
    pub access_token: Option<String>,
    pub token_expires_at: Option<DateTimeUtc>,
    pub server_url: Option<String>,
    pub token: Option<String>,
    pub encoding_aes_key: Option<String>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wx_auto_replies::Entity")]
    WxAutoReplies,
    #[sea_orm(has_many = "super::wx_menus::Entity")]
    WxMenus,
    #[sea_orm(has_many = "super::wx_messages::Entity")]
    WxMessages,
    #[sea_orm(has_many = "super::wx_users::Entity")]
    WxUsers,
}

impl Related<super::wx_auto_replies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAutoReplies.def()
    }
}

impl Related<super::wx_menus::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxMenus.def()
    }
}

impl Related<super::wx_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxMessages.def()
    }
}

impl Related<super::wx_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
