//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    pub openid: String,
    pub msg_id: Option<i64>,
    pub msg_type: String,
    pub direction: i8,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub media_id: Option<String>,
    pub pic_url: Option<String>,
    pub voice_format: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub recognition: Option<String>,
    pub thumb_media_id: Option<String>,
    pub msg_title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub msg_description: Option<String>,
    pub link_url: Option<String>,
    pub event_type: Option<String>,
    pub event_key: Option<String>,
    pub reply_msg_id: Option<i64>,
    pub is_auto_reply: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
