use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_materials")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    /// 素材类型：image/voice/video/thumb/news
    pub media_type: String,
    /// 微信素材ID
    pub media_id: Option<String>,
    /// 文件名称
    pub name: Option<String>,
    /// 文件URL（微信服务器地址）
    pub url: Option<String>,
    /// 本地存储路径
    pub local_path: Option<String>,
    /// 文件大小（字节）
    pub file_size: Option<i64>,
    /// 内容类型（MIME）
    pub content_type: Option<String>,
    /// 图片宽度（像素）
    pub width: Option<i32>,
    /// 图片高度（像素）
    pub height: Option<i32>,
    /// 视频时长（秒）
    pub duration: Option<i32>,
    /// 描述
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    /// 标题（视频/图文素材）
    pub title: Option<String>,
    /// 简介（视频素材）
    pub introduction: Option<String>,
    /// 缩略图素材ID
    pub thumb_media_id: Option<String>,
    /// 缩略图URL
    pub thumb_url: Option<String>,
    /// 图文消息原文链接
    pub content_source_url: Option<String>,
    /// 图文消息摘要
    pub digest: Option<String>,
    /// 作者
    pub author: Option<String>,
    /// 图文消息内容
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    /// 图文消息条目（JSON数组）
    #[sea_orm(column_type = "Text", nullable)]
    pub news_items: Option<String>,
    /// 是否永久素材：0-临时素材，1-永久素材
    pub is_permanent: i8,
    /// 同步状态：0-未同步，1-已同步
    pub sync_status: i8,
    /// 最近一次同步时间
    pub synced_at: Option<DateTimeUtc>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
