//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_pay_orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    pub out_trade_no: String,
    pub transaction_id: Option<String>,
    pub openid: String,
    pub body: String,
    pub total_fee: i64,
    pub fee_type: Option<String>,
    pub trade_type: String,
    pub spbill_create_ip: Option<String>,
    pub notify_url: String,
    pub prepay_id: Option<String>,
    pub code_url: Option<String>,
    pub mch_id: String,
    pub trade_state: Option<String>,
    pub trade_state_desc: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attach: Option<String>,
    pub time_expire: Option<DateTimeUtc>,
    pub paid_at: Option<DateTimeUtc>,
    pub status: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
