//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_pay_refunds")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    pub out_trade_no: String,
    pub out_refund_no: String,
    pub transaction_id: Option<String>,
    pub refund_id: Option<String>,
    pub total_fee: i64,
    pub refund_fee: i64,
    pub refund_reason: Option<String>,
    pub refund_status: Option<String>,
    pub refund_account: Option<String>,
    pub success_time: Option<DateTimeUtc>,
    pub status: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
