//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_template_logs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    pub template_id: String,
    pub openid: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub template_data: Option<String>,
    pub url: Option<String>,
    pub miniprogram_appid: Option<String>,
    pub miniprogram_pagepath: Option<String>,
    pub msg_id: Option<i64>,
    pub errcode: Option<i32>,
    pub errmsg: Option<String>,
    pub status: Option<i8>,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
