//! `SeaORM` Entity. Generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "wx_users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub account_id: i64,
    pub openid: String,
    pub unionid: Option<String>,
    pub nickname: Option<String>,
    pub sex: Option<i8>,
    pub city: Option<String>,
    pub country: Option<String>,
    pub province: Option<String>,
    pub language: Option<String>,
    pub headimgurl: Option<String>,
    pub subscribe_time: Option<DateTimeUtc>,
    pub unsubscribe_time: Option<DateTimeUtc>,
    pub subscribe_status: Option<i8>,
    pub remark: Option<String>,
    pub subscribe_scene: Option<String>,
    pub qr_scene: Option<String>,
    pub qr_scene_str: Option<String>,
    pub last_interact_time: Option<DateTimeUtc>,
    pub message_count: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wx_accounts::Entity",
        from = "Column::AccountId",
        to = "super::wx_accounts::Column::Id",
        on_update = "Restrict",
        on_delete = "Cascade"
    )]
    WxAccounts,
}

impl Related<super::wx_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WxAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
